name: CI

on:
  push:
    branches:
    - main
    - release/*
  pull_request:
    branches:
    - main

jobs:
  Build-ubuntu:
    name: Build ubuntu-latest
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
    - name: Install workloads
      run: dotnet workload install wasm-tools wasm-experimental
    - name: Build Release desktop
      run: dotnet build lols.desktop/lols.desktop.csproj --configuration Release
    - name: Build Release web
      run: dotnet build lols.web/lols.web.csproj --configuration Release

  Build-windows:
    name: Build windows-latest
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v1
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
    - name: Install workloads
      run: dotnet workload install wasm-tools wasm-experimental android ios
    - name: Build Release
      run: dotnet build --configuration Release

  Build-macos:
    name: Build macos-latest
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v1
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
    - name: Install workloads
      run: dotnet workload install wasm-tools wasm-experimental android ios
    - name: Build Release
      run: dotnet build --configuration Release
